// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlKtMc1nWQc6GKH-c4L9FxJm_yc8k5VMc',
    appId: '1:402362870125:web:6db900a3c0e894c71fd264',
    messagingSenderId: '402362870125',
    projectId: 'elearning-app-26c86',
    authDomain: 'elearning-app-26c86.firebaseapp.com',
    storageBucket: 'elearning-app-26c86.appspot.com',
    measurementId: 'G-YGRJPNCYM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ChHu-mwtk3AE1w7S4uj3OCeGW9_GRgY',
    appId: '1:402362870125:android:0b7d9f45c52e022a1fd264',
    messagingSenderId: '402362870125',
    projectId: 'elearning-app-26c86',
    storageBucket: 'elearning-app-26c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqV3TmHuX_nUwdhI1BNibjTUVRt3hxXo',
    appId: '1:402362870125:ios:4a2188f37af7a7f51fd264',
    messagingSenderId: '402362870125',
    projectId: 'elearning-app-26c86',
    storageBucket: 'elearning-app-26c86.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqqV3TmHuX_nUwdhI1BNibjTUVRt3hxXo',
    appId: '1:402362870125:ios:624e61fc844ca99e1fd264',
    messagingSenderId: '402362870125',
    projectId: 'elearning-app-26c86',
    storageBucket: 'elearning-app-26c86.appspot.com',
    iosBundleId: 'com.example.learningApp.RunnerTests',
  );
}
