// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaYbbvA4JLg1F4-k0o-cYih_I1UU0pJwI',
    appId: '1:19540626203:web:944b12e8d9e7082d0fe1be',
    messagingSenderId: '19540626203',
    projectId: 'atelier4-o-toughzaoui-iir5gx',
    authDomain: 'atelier4-o-toughzaoui-iir5gx.firebaseapp.com',
    storageBucket: 'atelier4-o-toughzaoui-iir5gx.appspot.com',
    measurementId: 'G-LZKJ4GMQMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfp6NoGn4STJAjP7Zcb91LUU3fYs4SuE',
    appId: '1:19540626203:android:8237ffc5c5a4f9d20fe1be',
    messagingSenderId: '19540626203',
    projectId: 'atelier4-o-toughzaoui-iir5gx',
    storageBucket: 'atelier4-o-toughzaoui-iir5gx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhX_qTnu9iz0KCLJLwXZMi1Qak5bzgcTg',
    appId: '1:19540626203:ios:f2b1ec03fa30993d0fe1be',
    messagingSenderId: '19540626203',
    projectId: 'atelier4-o-toughzaoui-iir5gx',
    storageBucket: 'atelier4-o-toughzaoui-iir5gx.appspot.com',
    iosBundleId: 'com.example.atelier4OToughzaouiIir5g4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhX_qTnu9iz0KCLJLwXZMi1Qak5bzgcTg',
    appId: '1:19540626203:ios:d6de3edb9a82f47d0fe1be',
    messagingSenderId: '19540626203',
    projectId: 'atelier4-o-toughzaoui-iir5gx',
    storageBucket: 'atelier4-o-toughzaoui-iir5gx.appspot.com',
    iosBundleId: 'com.example.atelier4OToughzaouiIir5g4.RunnerTests',
  );
}
